@create_investors.sql
@populate_investors.sql
@investor_city_view.sql
@create_investments.sql
@populate_investments.sql
@create_investment_data.sql
@populate_investment_data.sql
@investment_summary.sql
@investments_in_this_year.sql
@align.sql
@update_worth.sql
@holders.sql