CREATE OR REPLACE PACKAGE IRS IS
    FUNCTION ALIGN (first_string IN varchar2, desired_length IN NUMBER, direction IN varchar2) RETURN varchar2;
    FUNCTION MOST_WEALTHY_INVESTORS RETURN VARCHAR2;
    PROCEDURE SCALE_INVEST_AMOUNTS (entered_investment_id NUMBER, percent NUMBER);
    FUNCTION SHOW_INVESTORS (entered_investment_id NUMBER) RETURN VARCHAR2;
    PROCEDURE RECALCULATE_WORTH;
    PROCEDURE DECREASE_INVEST_AMOUNT (entered_investment_id NUMBER, difference NUMBER, dividor NUMBER);
END IRS;
/