CREATE OR REPLACE TRIGGER investors_cascade
  BEFORE DELETE ON INVESTORS
  FOR EACH ROW
  DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TRIGGER ONE_ENTRY_PRESENT DISABLE ';
    DELETE FROM INVESTMENT_DATA WHERE INVESTOR_ID = :OLD.ID;
    EXECUTE IMMEDIATE 'ALTER TRIGGER ONE_ENTRY_PRESENT ENABLE';
  END;


CREATE OR REPLACE TRIGGER investments_cascade
  BEFORE DELETE ON INVESTMENTS
  FOR EACH ROW
  DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TRIGGER ONE_ENTRY_PRESENT DISABLE ';
    DELETE FROM INVESTMENT_DATA WHERE INVESTMENT_ID = :OLD.ID;
    EXECUTE IMMEDIATE 'ALTER TRIGGER ONE_ENTRY_PRESENT ENABLE';
  END;
