CREATE OR REPLACE TRIGGER CHECK_MAX_TOTAL_INV_AMOUNT
  BEFORE UPDATE ON INVESTMENTS
  FOR EACH ROW
  BEGIN
    IF UPDATING('MAX_TOTAL_INVEST_AMOUNT') AND :NEW.MAX_TOTAL_INVEST_AMOUNT < :OLD.WORTH THEN
      RAISE_APPLICATION_ERROR(-20010, 'MAX_TOTAL_INVEST_AMOUNT (' || :NEW.MAX_TOTAL_INVEST_AMOUNT || ') CAN NOT BE LESS THAN ' || :OLD.WORTH);
    END IF;
  END;