CREATE OR REPLACE TRIGGER marked_investment_data
AFTER DELETE OR UPDATE ON INVESTMENT_DATA
FOR EACH ROW
  DECLARE
    m NUMBER;
  BEGIN
    SELECT MARKED
    INTO m
    FROM INVESTMENTS
    WHERE ID = :OLD.INVESTMENT_ID;

    IF m = 1
    THEN
      INSERT INTO INVESTMENT_DATA_COPY VALUES
        (INVESTMENT_DATA_COPY_SEQUENCE.nextval, :OLD.INVESTOR_ID, :OLD.INVESTMENT_ID, :OLD.INVESTMENT_DATE,
         :OLD.INVEST_AMOUNT);
    END IF;
  END;


