DROP SYNONYM holders;
DROP TABLE investment_data PURGE;
DROP TABLE investors PURGE;
DROP TABLE investments PURGE;
DROP VIEW investors_by_city;
DROP VIEW investment_summary;
DROP VIEW investments_in_current_year;
DROP PACKAGE IRS;

DROP FUNCTION MOST_WEALTHY_INVESTORA;
DROP FUNCTION  MOST_WEALTHY_INVESTORS;
DROP PROCEDURE RECALCULATE_WORTH;
DROP PROCEDURE SCALE_INVEST_AMOUNTS;
DROP FUNCTION SHOW_INVESTORS;
DROP FUNCTION TEST_FUNCTION;
DROP FUNCTION ALIGN;
DROP FUNCTION LEFTPAD;